# Generated by Django 4.2.4 on 2023-08-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='auctions.bids')),
            ],
        ),
    ]
