# Generated by Django 4.2.4 on 2023-09-06 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctions_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bids',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='url',
            field=models.URLField(),
        ),
    ]
