# Generated by Django 4.2.4 on 2023-09-06 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bids_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='last',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='start',
        ),
        migrations.AlterField(
            model_name='auctions',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bids',
            name='actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='auctions.auctions'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
