# Generated by Django 4.2.4 on 2023-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_auctions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
