# Generated by Django 4.2.4 on 2023-10-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auctions_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
